"""Pin the per-state frame cycles together across JS, tools and disk.

The cycle definitions live in index.html (STATE_ANIMS), the frame inventory in
tools/verify_sprites.py, and the pixels in sprites/ (generated by
tools/make_frames.py). Nothing at runtime couples them, so these tests do.
"""
import importlib.util
import json
import re
import sys
from pathlib import Path

import pytest
from PIL import Image

ROOT = Path(__file__).resolve().parents[1]
INDEX_HTML = ROOT / "src/squid_pet/frontend/index.html"
SPRITES = ROOT / "src/squid_pet/frontend/sprites"


def _load_tool(name):
    spec = importlib.util.spec_from_file_location(name, ROOT / "tools" / f"{name}.py")
    mod = importlib.util.module_from_spec(spec)
    sys.modules[name] = mod
    spec.loader.exec_module(mod)
    return mod


verify_sprites = _load_tool("verify_sprites")
make_frames = _load_tool("make_frames")
HTML = INDEX_HTML.read_text()


def _js_anims():
    """Parse STATE_ANIMS from index.html as {state: (frames, timeline)}."""
    m = re.search(r"const STATE_ANIMS = \{(.*?)\n    \};", HTML, re.DOTALL)
    assert m, "STATE_ANIMS not found in index.html"
    out = {}
    for state, n, t in re.findall(
        r"(\w+): \{ frames: (\d+), timeline: \[(.*?)\] \}", m.group(1), re.DOTALL
    ):
        out[state] = (int(n), json.loads("[" + t + "]"))
    return out


JS = _js_anims()


def test_js_states_match_inventory_and_generator():
    assert set(JS) == set(verify_sprites.STATE_FRAME_COUNTS) == set(make_frames.FRAMES)
    for state, (count, _) in JS.items():
        assert count == verify_sprites.STATE_FRAME_COUNTS[state]
        assert count == len(make_frames.FRAMES[state])


@pytest.mark.parametrize("state", sorted(JS))
def test_timeline_indices_are_valid_and_cover_every_frame(state):
    count, timeline = JS[state]
    used = {n for n, _ in timeline}
    assert used <= set(range(1, count + 1))
    assert used == set(range(1, count + 1)), "a generated frame is never shown"
    assert all(hold >= 50 for _, hold in timeline)


@pytest.mark.parametrize("state", sorted(JS))
def test_frames_exist_and_frame_one_is_the_base(state):
    count, _ = JS[state]
    for i in range(2, count + 1):
        assert (SPRITES / f"{state}_{i}.png").is_file()
    assert not (SPRITES / f"{state}_1.png").exists(), "frame 1 is the base sprite"
    assert make_frames.FRAMES[state][0] == [], "frame 1 must apply no edits"


@pytest.mark.parametrize("state", sorted(JS))
def test_frames_only_touch_their_edit_zones(state):
    base = Image.open(SPRITES / f"{state}.png").convert("RGBA")
    count, _ = JS[state]
    frames = [base] + [
        Image.open(SPRITES / f"{state}_{i}.png").convert("RGBA") for i in range(2, count + 1)
    ]
    assert make_frames.verify_state(state, base, frames) == []


def test_sprite_url_hands_back_the_cycle_frame():
    guard = HTML.index("if (_animSrc && _animKey === state) return _animSrc;")
    assert guard < HTML.index("return VALID.has(state)")


def test_stop_releases_ownership_before_restoring():
    body = HTML[HTML.index("function stopStateAnim"):]
    body = body[: body.index("\n    }\n")]
    assert body.index("_animSrc = null") < body.index("spriteUrl(currentState)")


def test_leaving_an_animated_state_does_not_restore_over_the_swap():
    assert "stopStateAnim(false)" in HTML
    assert "syncStateAnim();" in HTML


def test_mood_layer_drives_drowsy_and_sleeping_cycles():
    body = HTML[HTML.index("function _animVisualKey"):]
    body = body[: body.index("\n    }\n")]
    assert 'return _mood;' in body
    assert 'currentState === "approval_needed"' in body
    assert "_longWorking" in body, "long-running working belongs to the pancake cycle"
    for hook in ("function enterDrowsy", "function enterSleeping", "function wakeUpWithStretch"):
        start = HTML.index(hook)
        assert "syncStateAnim()" in HTML[start:start + 2500], hook


def test_every_animated_state_has_a_sprite_cycle_owner():
    """The states the cycler handles are real sprites (backend state or mood sprite)."""
    for state in JS:
        assert (SPRITES / f"{state}.png").is_file()
